/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.39
 * Generated at: 2019-11-26 14:04:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.page.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class userList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/E:/企业级实训/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/irs/WEB-INF/lib/shiro-all-1.2.3.jar!/META-INF/shiro.tld", Long.valueOf(1393324036000L));
    _jspx_dependants.put("/WEB-INF/lib/shiro-all-1.2.3.jar", Long.valueOf(1533017074000L));
    _jspx_dependants.put("jar:file:/E:/企业级实训/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/irs/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1533017074000L));
    _jspx_dependants.put("/WEB-INF/page/include/taglib.jsp", Long.valueOf(1533017074000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>用户列表</title>\r\n");
      out.write("<meta name=\"renderer\" content=\"webkit\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("<meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black\">\r\n");
      out.write("<meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"Cache-Control\" content=\"no-cache, must-revalidate\">\r\n");
      out.write("<meta http-equiv=\"expires\" content=\"Wed, 26 Feb 1997 08:21:57 GMT\">\r\n");
      out.write("<meta name=\"format-detection\" content=\"telephone=no\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/layui/css/layui.css\" media=\"all\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/font_eolqem241z66flxr.css\"\r\n");
      out.write("\tmedia=\"all\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/list.css\" media=\"all\" />\r\n");
      out.write("<script>\r\n");
      out.write("\tvar ctx = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"childrenBody\">\r\n");
      out.write("\t<blockquote class=\"layui-elem-quote news_search\">\r\n");
      out.write("\t\t<form class=\"layui-form\">\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<div class=\"layui-inline\">\r\n");
      out.write("\t\t\t\t\t<div class=\"layui-input-inline\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" id=\"nickname\" value=\"\" placeholder=\"请输入昵称\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"layui-input search_input\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"layui-input-inline layui-form\">\r\n");
      out.write("\t\t\t\t\t\t<select name=\"sex\" class=\"\" id=\"sex\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"-1\">请选择性别</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1\">男</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"0\">女</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2\">保密</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"layui-input-inline layui-form\">\r\n");
      out.write("\t\t\t\t\t\t<select name=\"status\" class=\"\" id=\"status\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"-1\">请选择账户状态</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"0\">未激活</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1\">正常</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2\">禁用</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"margin-top: 1%\">\r\n");
      out.write("\t\t\t\t<div class=\"layui-inline\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"createTimeStart\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"layui-input userName\" name=\"createTimeStart\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"注册时间(开始)\" value=\"\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"layui-inline\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"createTimeEnd\" class=\"layui-input userName\"\r\n");
      out.write("\t\t\t\t\t\tname=\"createTimeEnd\" placeholder=\"注册时间(结束)\" value=\"\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<a class=\"layui-btn search_btn\" lay-submit=\"\" data-type=\"search\"\r\n");
      out.write("\t\t\t\t\tlay-filter=\"search\">查询</a>\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_shiro_005fhasPermission_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_shiro_005fhasPermission_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"layui-inline\">（支持模糊查询）</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t</blockquote>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<div class=\"layui-form\">\r\n");
      out.write("\t\t<table id=\"userList\" lay-filter=\"userList\"></table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/layui/layui.js\"></script>\r\n");
      out.write("\t<script type=\"text/html\" id=\"barEdit\">\r\n");
      out.write("  \t\t<a class=\"layui-btn layui-btn-xs\" lay-event=\"edit\">编辑</a>\r\n");
      out.write("  \t\t<a class=\"layui-btn layui-btn-danger layui-btn-xs\" lay-event=\"del\">删除</a>\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script type=\"text/html\" id=\"sexTpl\">\r\n");
      out.write(" \t\t {{#  if(d.sex === '0'){ }}\r\n");
      out.write("   \t\t <span style=\"color: #F581B1;\">女</span>\r\n");
      out.write("  \t\t{{#  } else if(d.sex === '1'){ }}\r\n");
      out.write("   \t\t \t男\r\n");
      out.write("\t\t{{#  } else{ }}\r\n");
      out.write("   \t\t \t保密\r\n");
      out.write("  \t\t{{#  } }}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script type=\"text/html\" id=\"statusTpl\">\r\n");
      out.write(" \t\t {{#  if(d.status === '0'){ }}\r\n");
      out.write("   \t\t <span style=\"color: #FFB800;\">未激活</span>\r\n");
      out.write("  \t\t{{#  } else if(d.status === '1'){ }}\r\n");
      out.write("\t\t\t<span style=\"color: #01AAED;\">正常</span>\r\n");
      out.write("\t\t{{#  } else{ }}\r\n");
      out.write("   \t\t \t<span style=\"color: #FF5722;\">禁用</span>\r\n");
      out.write("  \t\t{{#  } }}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tlayui\r\n");
      out.write("\t\t\t\t.config({\r\n");
      out.write("\t\t\t\t\tbase : \"js/\"\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t.use(\r\n");
      out.write("\t\t\t\t\t\t[ 'form', 'layer', 'jquery', 'table', 'laydate' ],\r\n");
      out.write("\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\tvar form = layui.form, table = layui.table, layer = parent.layer === undefined ? layui.layer\r\n");
      out.write("\t\t\t\t\t\t\t\t\t: parent.layer, laydate = layui.laydate\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$ = layui.jquery,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tnowTime = new Date().valueOf(),\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmax = null,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tactive = {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsearch : function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar nickname = $('#nickname'), sex = $('#sex option:selected'), status = $('#status option:selected');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tcreateTimeStart = $(\"#createTimeStart\"),\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tcreateTimeEnd = $(\"#createTimeEnd\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t//执行重载\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttable\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t.reload(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'userList',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tpage : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tcurr : 1\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t//重新从第 1 页开始\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\twhere : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t//key: {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tnickname : nickname\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.val(),\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tsex : sex\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.val(),\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tstatus : status\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.val(),\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tcreateTimeStart : createTimeStart\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.val(),\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tcreateTimeEnd : createTimeEnd\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.val()\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t//}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tvar start = laydate.render({\r\n");
      out.write("\t\t\t\t\t\t\t\telem : '#createTimeStart',\r\n");
      out.write("\t\t\t\t\t\t\t\ttype : 'datetime',\r\n");
      out.write("\t\t\t\t\t\t\t\tmax : nowTime,\r\n");
      out.write("\t\t\t\t\t\t\t\tbtns : [ 'clear', 'confirm' ],\r\n");
      out.write("\t\t\t\t\t\t\t\tdone : function(value, date) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tendMax = end.config.max;\r\n");
      out.write("\t\t\t\t\t\t\t\t\tend.config.min = date;\r\n");
      out.write("\t\t\t\t\t\t\t\t\tend.config.min.month = date.month - 1;\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\tvar end = laydate.render({\r\n");
      out.write("\t\t\t\t\t\t\t\telem : '#createTimeEnd',\r\n");
      out.write("\t\t\t\t\t\t\t\ttype : 'datetime',\r\n");
      out.write("\t\t\t\t\t\t\t\tmax : nowTime,\r\n");
      out.write("\t\t\t\t\t\t\t\tdone : function(value, date) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif ($.trim(value) == '') {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar curDate = new Date();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdate = {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t'date' : curDate.getDate(),\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t'month' : curDate.getMonth() + 1,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t'year' : curDate.getFullYear()\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstart.config.max = date;\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstart.config.max.month = date.month - 1;\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t})\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t//加载页面数据\r\n");
      out.write("\t\t\t\t\t\t\ttable\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.render({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid : 'userList',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\telem : '#userList',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\turl : ctx + '/user/getUserList' //数据接口\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tlimit : 10//每页默认数\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tlimits : [ 10, 20, 30, 40 ],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tcols : [ [ //表头\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttype : 'checkbox'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tfield : 'uid',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttitle : 'ID',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\twidth : 60\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tfield : 'eMail',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttitle : '邮箱'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tfield : 'nickname',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttitle : '昵称'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tfield : 'sex',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttitle : '性别',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttemplet : '#sexTpl'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tfield : 'birthday',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttitle : '出生日期',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttemplet : '<div>{{ formatTime(d.birthday,\"yyyy-MM-dd\")}}</div>'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tfield : 'address',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttitle : '地址'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tfield : 'phone',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttitle : '手机',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\twidth : 120\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tfield : 'status',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttitle : '状态',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttemplet : '#statusTpl'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tfield : 'createTime',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttitle : '注册日期',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttemplet : '<div>{{ formatTime(d.createTime,\"yyyy-MM-dd hh:mm:ss\")}}</div>'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t}, {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttitle : '操作',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttoolbar : '#barEdit'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t} ] ],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tpage : true\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t,where: {timestamp: (new Date()).valueOf()}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t//开启分页\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t//监听工具条\r\n");
      out.write("\t\t\t\t\t\t\ttable.on('tool(userList)', function(obj) {\r\n");
      out.write("\t\t\t\t\t\t\t\tvar data = obj.data;\r\n");
      out.write("\t\t\t\t\t\t\t\tif (obj.event === 'del') {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tlayer.confirm('真的删除行么', function(index) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\turl : ctx + '/user/delUserByUid/'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t+ data.uid,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsuccess : function(d) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tif (d.code == 0) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tobj.del();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tlayer.msg(data.msg, {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\ticon : 5\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tlayer.close(index);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t} else if (obj.event === 'edit') {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tlayer.open({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype : 2,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttitle : \"编辑用户\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tarea : [ '400px', '500px' ],\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tcontent : ctx + \"/user/editUser/\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ data.uid //这里content是一个普通的String\r\n");
      out.write("\t\t\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t//查询\r\n");
      out.write("\t\t\t\t\t\t\t$(\".search_btn\").click(function() {\r\n");
      out.write("\t\t\t\t\t\t\t\tvar type = $(this).data('type');\r\n");
      out.write("\t\t\t\t\t\t\t\tactive[type] ? active[type].call(this) : '';\r\n");
      out.write("\t\t\t\t\t\t\t})\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t//添加文章\r\n");
      out.write("\t\t\t\t\t\t\t$(\".userAdd_btn\").click(function() {\r\n");
      out.write("\t\t\t\t\t\t\t\tvar index = layui.layer.open({\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle : \"添加文章\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttype : 2,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcontent : ctx + \"/user/addUser\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsuccess : function(layero, index) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t\t\t//改变窗口大小时，重置弹窗的高度，防止超出可视区域（如F12调出debug的操作）\r\n");
      out.write("\t\t\t\t\t\t\t\t$(window).resize(function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tlayui.layer.full(index);\r\n");
      out.write("\t\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t\t\tlayui.layer.full(index);\r\n");
      out.write("\t\t\t\t\t\t\t})\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t//批量删除\r\n");
      out.write("\t\t\t\t\t\t\t$(\".batchDel\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.click(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvar checkStatus = table\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t.checkStatus('userList'), data = checkStatus.data, userStr = '';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tif (data.length > 0) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t$.each(data, function(n,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvalue) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tuserStr += value.uid\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ ',';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tuserStr = userStr\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.substring(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tuserStr.length - 1);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tlayer\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.confirm(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t'确定删除<strong>'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ data.length\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ '</strong>条数据吗？',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfunction(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tindex) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t//调用删除接口\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\turl : ctx\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ '/user/delUsers/'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ userStr,//接口地址\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tsuccess : function(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\td) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tif (d.code == 0) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t//删除成功，刷新父页面\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tparent.location\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.reload();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tlayer\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.msg(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"权限不足，联系超管！\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ticon : 5\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tlayer.msg(\"请选择需要删除的用户\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t})\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t})\r\n");
      out.write("\r\n");
      out.write("\t\t//格式化时间\r\n");
      out.write("\t\tfunction formatTime(datetime, fmt) {\r\n");
      out.write("\t\t\tif (datetime == null || datetime == 0) {\r\n");
      out.write("\t\t\t\treturn \"\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (parseInt(datetime) == datetime) {\r\n");
      out.write("\t\t\t\tif (datetime.length == 10) {\r\n");
      out.write("\t\t\t\t\tdatetime = parseInt(datetime) * 1000;\r\n");
      out.write("\t\t\t\t} else if (datetime.length == 13) {\r\n");
      out.write("\t\t\t\t\tdatetime = parseInt(datetime);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tdatetime = new Date(datetime);\r\n");
      out.write("\t\t\tvar o = {\r\n");
      out.write("\t\t\t\t\"M+\" : datetime.getMonth() + 1, //月份   \r\n");
      out.write("\t\t\t\t\"d+\" : datetime.getDate(), //日   \r\n");
      out.write("\t\t\t\t\"h+\" : datetime.getHours(), //小时   \r\n");
      out.write("\t\t\t\t\"m+\" : datetime.getMinutes(), //分   \r\n");
      out.write("\t\t\t\t\"s+\" : datetime.getSeconds(), //秒   \r\n");
      out.write("\t\t\t\t\"q+\" : Math.floor((datetime.getMonth() + 3) / 3), //季度   \r\n");
      out.write("\t\t\t\t\"S\" : datetime.getMilliseconds()\r\n");
      out.write("\t\t\t//毫秒   \r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\tif (/(y+)/.test(fmt))\r\n");
      out.write("\t\t\t\tfmt = fmt.replace(RegExp.$1, (datetime.getFullYear() + \"\")\r\n");
      out.write("\t\t\t\t\t\t.substr(4 - RegExp.$1.length));\r\n");
      out.write("\t\t\tfor ( var k in o)\r\n");
      out.write("\t\t\t\tif (new RegExp(\"(\" + k + \")\").test(fmt))\r\n");
      out.write("\t\t\t\t\tfmt = fmt.replace(RegExp.$1,\r\n");
      out.write("\t\t\t\t\t\t\t(RegExp.$1.length == 1) ? (o[k]) : ((\"00\" + o[k])\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.substr((\"\" + o[k]).length)));\r\n");
      out.write("\t\t\treturn fmt;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/page/include/taglib.jsp(2,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("ctx");
      // /WEB-INF/page/include/taglib.jsp(2,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/page/include/taglib.jsp(2,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_shiro_005fhasPermission_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  shiro:hasPermission
    org.apache.shiro.web.tags.HasPermissionTag _jspx_th_shiro_005fhasPermission_005f0 = (org.apache.shiro.web.tags.HasPermissionTag) _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.get(org.apache.shiro.web.tags.HasPermissionTag.class);
    boolean _jspx_th_shiro_005fhasPermission_005f0_reused = false;
    try {
      _jspx_th_shiro_005fhasPermission_005f0.setPageContext(_jspx_page_context);
      _jspx_th_shiro_005fhasPermission_005f0.setParent(null);
      // /WEB-INF/page/user/userList.jsp(67,4) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_shiro_005fhasPermission_005f0.setName("user:user:save");
      int _jspx_eval_shiro_005fhasPermission_005f0 = _jspx_th_shiro_005fhasPermission_005f0.doStartTag();
      if (_jspx_eval_shiro_005fhasPermission_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<div class=\"layui-inline\">\r\n");
          out.write("\t\t\t\t\t\t<a class=\"layui-btn layui-btn-normal userAdd_btn\">添加用户</a>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_shiro_005fhasPermission_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_shiro_005fhasPermission_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f0);
      _jspx_th_shiro_005fhasPermission_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_shiro_005fhasPermission_005f0, _jsp_getInstanceManager(), _jspx_th_shiro_005fhasPermission_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_shiro_005fhasPermission_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  shiro:hasPermission
    org.apache.shiro.web.tags.HasPermissionTag _jspx_th_shiro_005fhasPermission_005f1 = (org.apache.shiro.web.tags.HasPermissionTag) _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.get(org.apache.shiro.web.tags.HasPermissionTag.class);
    boolean _jspx_th_shiro_005fhasPermission_005f1_reused = false;
    try {
      _jspx_th_shiro_005fhasPermission_005f1.setPageContext(_jspx_page_context);
      _jspx_th_shiro_005fhasPermission_005f1.setParent(null);
      // /WEB-INF/page/user/userList.jsp(72,4) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_shiro_005fhasPermission_005f1.setName("user:user:delete");
      int _jspx_eval_shiro_005fhasPermission_005f1 = _jspx_th_shiro_005fhasPermission_005f1.doStartTag();
      if (_jspx_eval_shiro_005fhasPermission_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<div class=\"layui-inline\">\r\n");
          out.write("\t\t\t\t\t\t<a class=\"layui-btn layui-btn-danger batchDel\">批量删除</a>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_shiro_005fhasPermission_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_shiro_005fhasPermission_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fshiro_005fhasPermission_0026_005fname.reuse(_jspx_th_shiro_005fhasPermission_005f1);
      _jspx_th_shiro_005fhasPermission_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_shiro_005fhasPermission_005f1, _jsp_getInstanceManager(), _jspx_th_shiro_005fhasPermission_005f1_reused);
    }
    return false;
  }
}
